#include "project.h"
#include "toml_parser.h"
#include "ui.h"
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <filesystem>

#ifndef ORBIT_VERSION
  #define ORBIT_VERSION "0.1.0"
#endif

namespace fs = std::filesystem;

// ── Load Manifest ─────────────────────────────────────────────────────────────

Manifest load_manifest(const std::string& project_dir) {
    fs::path root(project_dir);
    fs::path toml_path = root / "orbit.toml";

    if (!fs::exists(toml_path)) {
        throw std::runtime_error(
            "orbit.toml not found in: " + project_dir +
            "\n  Run 'orbit init' to create a new project."
        );
    }

    toml::Table tbl;
    try {
        tbl = toml::parse_file(toml_path.string());
    } catch (const std::exception& e) {
        throw std::runtime_error("Failed to parse orbit.toml: " + std::string(e.what()));
    }

    Manifest m;
    m.manifest_path = toml_path.string();
    m.project_root  = fs::canonical(root).string();

    // [package]
    const toml::Table* pkg = toml::get_subtable(tbl, "package");
    if (!pkg) throw std::runtime_error("orbit.toml is missing [package] section.");

    m.name         = toml::get_string(*pkg, "name");
    m.version      = toml::get_string(*pkg, "version", "0.1.0");
    m.author       = toml::get_string(*pkg, "author");
    m.description  = toml::get_string(*pkg, "description");
    m.license      = toml::get_string(*pkg, "license", "MIT");
    m.nova_version = toml::get_string(*pkg, "nova_version");

    if (m.name.empty())
        throw std::runtime_error("orbit.toml [package] is missing 'name'.");

    // [build]
    const toml::Table* build = toml::get_subtable(tbl, "build");
    if (build) {
        m.entry_point  = toml::get_string(*build, "entry",   "src/main.npp");
        m.output_name  = toml::get_string(*build, "output",  m.name);
        m.type         = toml::get_string(*build, "type",    "binary");
        m.sources      = toml::get_string_array(*build, "extra_sources");
        m.include_dirs = toml::get_string_array(*build, "include_dirs");
    } else {
        m.entry_point = "src/main.npp";
        m.output_name = m.name;
        m.type        = "binary";
    }

    // [profile.dev]
    const toml::Table* profiles = toml::get_subtable(tbl, "profile");
    if (profiles) {
        const toml::Table* dev = toml::get_subtable(*profiles, "dev");
        if (dev) {
            m.dev.opt_level = (int)toml::get_int(*dev, "opt_level", 0);
            m.dev.debug     = toml::get_bool(*dev, "debug", true);
        }
        const toml::Table* rel = toml::get_subtable(*profiles, "release");
        if (rel) {
            m.release.opt_level = (int)toml::get_int(*rel, "opt_level", 3);
            m.release.debug     = toml::get_bool(*rel, "debug", false);
        }
    } else {
        m.dev.opt_level = 0;
        m.dev.debug     = true;
        m.release.opt_level = 3;
        m.release.debug     = false;
    }

    // [dependencies]
    const toml::Table* deps = toml::get_subtable(tbl, "dependencies");
    if (deps) {
        for (const auto& [dep_name, dep_val] : *deps) {
            Dependency d;
            d.name = dep_name;

            if (dep_val.type == toml::Value::Type::Table) {
                d.local_path = toml::get_string(dep_val.tbl, "local");
                d.url        = toml::get_string(dep_val.tbl, "url");
                d.version    = toml::get_string(dep_val.tbl, "version");
            } else {
                // Simple string shorthand: dep = "1.0.0" or dep = "./path"
                std::string val = dep_val.as_string();
                if (!val.empty() && (val[0] == '.' || val[0] == '/')) {
                    d.local_path = val;
                } else if (val.find("://") != std::string::npos) {
                    d.url = val;
                } else {
                    d.version = val;
                }
            }
            m.dependencies.push_back(d);
        }
    }

    return m;
}

// ── Write Default Manifest ────────────────────────────────────────────────────

void write_default_manifest(const std::string& project_dir,
                             const std::string& name,
                             const std::string& type) {
    fs::path toml_path = fs::path(project_dir) / "orbit.toml";
    std::ofstream f(toml_path);
    if (!f.is_open())
        throw std::runtime_error("Cannot write orbit.toml to: " + project_dir);

    f << "# orbit.toml — Nova project manifest\n";
    f << "# Generated by Orbit " << ORBIT_VERSION << "\n\n";

    f << "[package]\n";
    f << "name        = \"" << name << "\"\n";
    f << "version     = \"0.1.0\"\n";
    f << "author      = \"\"\n";
    f << "description = \"\"\n";
    f << "license     = \"MIT\"\n\n";

    f << "[build]\n";
    if (type == "library") {
        f << "type   = \"library\"\n";
        f << "entry  = \"src/lib.npp\"\n";
        f << "output = \"" << name << "\"\n";
    } else {
        f << "type   = \"binary\"\n";
        f << "entry  = \"src/main.npp\"\n";
        f << "output = \"" << name << "\"\n";
    }
    f << "\n";

    f << "[profile.dev]\n";
    f << "opt_level = 0\n";
    f << "debug     = true\n\n";

    f << "[profile.release]\n";
    f << "opt_level = 3\n";
    f << "debug     = false\n\n";

    f << "[dependencies]\n";
    f << "# Add dependencies like:\n";
    f << "#   mylib = { local = \"./libs/mylib\" }\n";
    f << "#   mylib = { url   = \"https://example.com/mylib.orbit\" }\n";
    f << "\n";
}
